### ISSUE TITLE
Error when starting Spigot / MC 1.21.3

### ISSUE THREAD

**Issue by pschapman** [zombieman33/NightVisionPlus#1]
Getting this error when starting server with NVP 2.2.5.

```
[15:46:14] [Server thread/INFO]: [NightVisionPlus] Enabling NightVisionPlus v2.2.5
[15:46:14] [Server thread/ERROR]: Error occurred while enabling NightVisionPlus v2.2.5 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/event/HoverEventSource
        at me.zombieman.nightvisionplus.NightVisionPlus.onEnable(NightVisionPlus.java:33) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4388-Spigot-e65d67a-066a74e]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4388-Spigot-e65d67a-066a74e]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:656) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4388-Spigot-e65d67a-066a74e]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4388-Spigot-e65d67a-066a74e]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:268) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4388-Spigot-e65d67a-066a74e]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4388-Spigot-e65d67a-066a74e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4388-Spigot-e65d67a-066a74e]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.event.HoverEventSource
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 12 more
```

**Comment by zombieman33** [comment]
Have you tried with NVP 2.2.7?
Also is your server completely up to date?

**Comment by pschapman** [comment]
Yes. Patched today. Spigot 1.21.4 / NVP 2.2.7 / Ubuntu server 24.04 LTS with current patches.
